version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: serviceorders-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong_password123"
    ports:
      - "1433:1433"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: serviceorders-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8080"
      Database__Provider: "SqlServer"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=ServiceOrdersDb;User Id=sa;Password=Your_strong_password123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      - db
